/**
 * A curated list of well-known global tickers, used only as a fuzzy-match
 * fallback when Yahoo's search returns zero results — e.g. a typo like
 * "relience" won't prefix-match "Reliance Industries" on Yahoo's index, but
 * a small edit-distance check against this list still finds it.
 */
export interface KnownCompany {
  symbol: string;
  name: string;
}

export const KNOWN_COMPANIES: KnownCompany[] = [
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corporation" },
  { symbol: "GOOG", name: "Alphabet Inc." },
  { symbol: "AMZN", name: "Amazon.com, Inc." },
  { symbol: "NVDA", name: "NVIDIA Corporation" },
  { symbol: "META", name: "Meta Platforms, Inc." },
  { symbol: "TSLA", name: "Tesla, Inc." },
  { symbol: "BRK-B", name: "Berkshire Hathaway Inc." },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "MA", name: "Mastercard Incorporated" },
  { symbol: "UNH", name: "UnitedHealth Group Incorporated" },
  { symbol: "XOM", name: "Exxon Mobil Corporation" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "PG", name: "Procter & Gamble Company" },
  { symbol: "HD", name: "Home Depot, Inc." },
  { symbol: "ORCL", name: "Oracle Corporation" },
  { symbol: "KO", name: "Coca-Cola Company" },
  { symbol: "PEP", name: "PepsiCo, Inc." },
  { symbol: "NFLX", name: "Netflix, Inc." },
  { symbol: "AMD", name: "Advanced Micro Devices, Inc." },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "CRM", name: "Salesforce, Inc." },
  { symbol: "INTC", name: "Intel Corporation" },
  { symbol: "CSCO", name: "Cisco Systems, Inc." },
  { symbol: "IBM", name: "International Business Machines Corporation" },
  { symbol: "QCOM", name: "QUALCOMM Incorporated" },
  { symbol: "TXN", name: "Texas Instruments Incorporated" },
  { symbol: "PYPL", name: "PayPal Holdings, Inc." },
  { symbol: "UBER", name: "Uber Technologies, Inc." },
  { symbol: "ABNB", name: "Airbnb, Inc." },
  { symbol: "SHOP", name: "Shopify Inc." },
  { symbol: "SQ", name: "Block, Inc." },
  { symbol: "SPOT", name: "Spotify Technology S.A." },
  { symbol: "SNAP", name: "Snap Inc." },
  { symbol: "PINS", name: "Pinterest, Inc." },
  { symbol: "BA", name: "Boeing Company" },
  { symbol: "DIS", name: "Walt Disney Company" },
  { symbol: "NKE", name: "Nike, Inc." },
  { symbol: "MCD", name: "McDonald's Corporation" },
  { symbol: "SBUX", name: "Starbucks Corporation" },
  { symbol: "GS", name: "Goldman Sachs Group, Inc." },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "BAC", name: "Bank of America Corporation" },
  { symbol: "WFC", name: "Wells Fargo & Company" },
  { symbol: "C", name: "Citigroup Inc." },
  { symbol: "T", name: "AT&T Inc." },
  { symbol: "VZ", name: "Verizon Communications Inc." },
  { symbol: "PFE", name: "Pfizer Inc." },
  { symbol: "MRK", name: "Merck & Co., Inc." },
  { symbol: "ABBV", name: "AbbVie Inc." },
  { symbol: "LLY", name: "Eli Lilly and Company" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc." },
  { symbol: "COST", name: "Costco Wholesale Corporation" },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "TM", name: "Toyota Motor Corporation" },
  { symbol: "F", name: "Ford Motor Company" },
  { symbol: "GM", name: "General Motors Company" },
  { symbol: "RIVN", name: "Rivian Automotive, Inc." },
  { symbol: "LCID", name: "Lucid Group, Inc." },
  { symbol: "PLTR", name: "Palantir Technologies Inc." },
  { symbol: "COIN", name: "Coinbase Global, Inc." },
  { symbol: "MSTR", name: "MicroStrategy Incorporated" },
  { symbol: "ASML", name: "ASML Holding N.V." },
  { symbol: "SAP", name: "SAP SE" },
  { symbol: "TSM", name: "Taiwan Semiconductor Manufacturing Company" },
  { symbol: "BABA", name: "Alibaba Group Holding Limited" },
  { symbol: "JD", name: "JD.com, Inc." },
  { symbol: "PDD", name: "PDD Holdings Inc." },
  { symbol: "NTES", name: "NetEase, Inc." },
  { symbol: "RELIANCE.NS", name: "Reliance Industries Limited" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services Limited" },
  { symbol: "INFY", name: "Infosys Limited" },
  { symbol: "HDB", name: "HDFC Bank Limited" },
  { symbol: "IBN", name: "ICICI Bank Limited" },
  { symbol: "WIT", name: "Wipro Limited" },
  { symbol: "SBIN.NS", name: "State Bank of India" },
  { symbol: "ITC.NS", name: "ITC Limited" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever Limited" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel Limited" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises Limited" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors Limited" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki India Limited" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints Limited" },
  { symbol: "SONY", name: "Sony Group Corporation" },
  { symbol: "NVS", name: "Novartis AG" },
  { symbol: "AZN", name: "AstraZeneca PLC" },
  { symbol: "SHEL", name: "Shell plc" },
  { symbol: "BP", name: "BP p.l.c." },
  { symbol: "UL", name: "Unilever PLC" },
  { symbol: "NSRGY", name: "Nestle S.A." },
  { symbol: "TTE", name: "TotalEnergies SE" },
  { symbol: "SIEGY", name: "Siemens AG" },
  { symbol: "VWAGY", name: "Volkswagen AG" },
  { symbol: "MUFG", name: "Mitsubishi UFJ Financial Group, Inc." },
  { symbol: "HMC", name: "Honda Motor Co., Ltd." },
  { symbol: "SNY", name: "Sanofi" },
  { symbol: "RY", name: "Royal Bank of Canada" },
  { symbol: "TD", name: "Toronto-Dominion Bank" },
  { symbol: "BHP", name: "BHP Group Limited" },
  { symbol: "RIO", name: "Rio Tinto Group" },
  { symbol: "GE", name: "General Electric Company" },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "DE", name: "Deere & Company" },
  { symbol: "HON", name: "Honeywell International Inc." },
  { symbol: "LMT", name: "Lockheed Martin Corporation" },
  { symbol: "RTX", name: "RTX Corporation" },
  { symbol: "UPS", name: "United Parcel Service, Inc." },
  { symbol: "FDX", name: "FedEx Corporation" },
  { symbol: "LOW", name: "Lowe's Companies, Inc." },
  { symbol: "TGT", name: "Target Corporation" },
  { symbol: "CVX", name: "Chevron Corporation" },
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "SLB", name: "Schlumberger Limited" },
  { symbol: "MO", name: "Altria Group, Inc." },
  { symbol: "PM", name: "Philip Morris International Inc." },
  { symbol: "CL", name: "Colgate-Palmolive Company" },
  { symbol: "KHC", name: "Kraft Heinz Company" },
  { symbol: "MDLZ", name: "Mondelez International, Inc." },
  { symbol: "GIS", name: "General Mills, Inc." },
  { symbol: "EA", name: "Electronic Arts Inc." },
  { symbol: "ATVI", name: "Activision Blizzard, Inc." },
  { symbol: "TTWO", name: "Take-Two Interactive Software, Inc." },
  { symbol: "RBLX", name: "Roblox Corporation" },
  { symbol: "ZM", name: "Zoom Video Communications, Inc." },
  { symbol: "DOCU", name: "DocuSign, Inc." },
  { symbol: "TWLO", name: "Twilio Inc." },
  { symbol: "SNOW", name: "Snowflake Inc." },
  { symbol: "DDOG", name: "Datadog, Inc." },
  { symbol: "NET", name: "Cloudflare, Inc." },
  { symbol: "CRWD", name: "CrowdStrike Holdings, Inc." },
  { symbol: "PANW", name: "Palo Alto Networks, Inc." },
  { symbol: "FTNT", name: "Fortinet, Inc." },
  { symbol: "NOW", name: "ServiceNow, Inc." },
  { symbol: "WDAY", name: "Workday, Inc." },
  { symbol: "TEAM", name: "Atlassian Corporation" },
  { symbol: "ZS", name: "Zscaler, Inc." },
  { symbol: "OKTA", name: "Okta, Inc." },
  { symbol: "MDB", name: "MongoDB, Inc." },
  { symbol: "HOOD", name: "Robinhood Markets, Inc." },
  { symbol: "SOFI", name: "SoFi Technologies, Inc." },
  { symbol: "AFRM", name: "Affirm Holdings, Inc." },
  { symbol: "DASH", name: "DoorDash, Inc." },
  { symbol: "LYFT", name: "Lyft, Inc." },
  { symbol: "ETSY", name: "Etsy, Inc." },
  { symbol: "EBAY", name: "eBay Inc." },
  { symbol: "BIDU", name: "Baidu, Inc." },
  { symbol: "XPEV", name: "XPeng Inc." },
  { symbol: "NIO", name: "NIO Inc." },
  { symbol: "LI", name: "Li Auto Inc." },
  { symbol: "GME", name: "GameStop Corp." },
  { symbol: "AMC", name: "AMC Entertainment Holdings, Inc." },
  { symbol: "BB", name: "BlackBerry Limited" },
  { symbol: "NOK", name: "Nokia Corporation" },
  { symbol: "ERIC", name: "Telefonaktiebolaget LM Ericsson" },
];
